printjson(db.people.insertOne(
    {
        "sex":"Male",
        "first_name":"Prashant",
        "last_name":"Jha",
        "job":"Software Engineerr",
        "email":"s21428@pjwstk.edu.pl",
        "location":{
            "city":"Warszawa",
            "address":{
                "streetname":"Sluzby",
                "streetnumber":"1"}
            },
        "description":"NBD",
        "height":"169.5",
        "weight":"82.5",
        "birth_date":"1991-10-20T00:00:00Z",
        "nationality":"India",
        "credit":[
            {
                "type":"visa",
                "number":"76457457573763",
                "currency":"USD",
                "balance":"1435432"
            }
        ]
    }
))
